path: assets/dataset
train: train # 指向訓練集圖片路徑
val: valid # 指向驗證集圖片路徑
test: test # (選填) 測試集

nc: 1
names: ["0"]

roboflow:
  workspace: joanne-mkuka
  project: drone-cmxwz-rcp4v
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/joanne-mkuka/drone-cmxwz-rcp4v/dataset/1
